Create pubsub topics in ci-iam fixture project
Fixes:

    Error: Error creating Topic: googleapi: Error 400: The topic
    projects/test-iam-prj-0-2e37/topics/test-iam-tpc-1-c7ef cannot be
    created or updated due to an organization policy specified at the
    project or organization level. The organization policy does not allow
    message storage in any GCP region where Cloud Pub/Sub is present. The
    organization policy may be updated by your project or organization
    administrator. See
    https://console.cloud.google.com/iam-admin/orgpolicies/gcp-resourceLocations?project=test-iam-prj-0-2e37.
    If the topic's project was recently created, you may need to wait a few
    minutes for the project's organization policy to be properly
    initialized, and then retry this operation.

    on base/main.tf line 100, in resource "google_pubsub_topic" "test":
    100: resource "google_pubsub_topic" "test" {