Fix terraform validate 0.12 failure
Without this patch terraform 0.12.3 validation fails with:

    test/terraform_validate ./test/fixtures/full
    Error: Reference to undeclared local value
      on outputs.tf line 64, in output "subnets":
      64:   value       = local.subnets
    A local value with the name "subnets" has not been declared.