Use unique test folder names
Without this patch CI fails with the following message.  This patch
fixes the issue by using unique names in the same format as other
resources in the test suite.

    Error: Error creating folder 'Test IAM Folder 0' in
    'folders/547412473096': Error waiting for creating folder: Error
    code 9, message: Folder reservation failed for parent
    [folders/547412473096], folder [] and displayName [Test IAM Folder
    0] due to constraint: The folder operation violates display name
    uniqueness within the parent.